project_id = "rxsovhyimflzvxggppal"

[functions.ai-mentor]
verify_jwt = false

[functions.create-checkout]
verify_jwt = false

[functions.check-subscription]
verify_jwt = false

[functions.customer-portal]
verify_jwt = false

[functions.send-contact]
verify_jwt = false
